version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - asmahood
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - asmahood
