version: "3.9"
services:
  api:
    build: .
    command: ./api
    volumes:
      - .:/usr/api
    ports:
      - 5000:5000
    depends_on:
      - db
    environment:
      - PORT=5000
    networks:
      - services

  db:
    image: postgres:12.2-alpine
    volumes:
      - ./scripts/create-databases.sh:/docker-entrypoint-initdb.d/create-databases.sh
      - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=password
      - DATABASES=uwpokerclub
      - DATABASE_ENVS=development,test
    ports:
      - 5432:5432
    networks:
      - services
volumes:
  postgres-data:
networks:
  services:
    name: uwpokerclub_services_network