name: Continous Integration
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create docker network
      run: docker network create uwpokerclub_services_network
    - name: Build image
      run: docker compose build
    - name: Start containers
      run: docker compose up -d
    - name: Debug
      run: docker compose exec server echo $TEST_DATABASE_URL
    - name: Run migrations
      run: docker compose exec server ./scripts/migrate.sh --test up
    - name: Run tests
      run: docker compose exec server go test -v -p=1 ./internal/...
    - name: Teardown containers
      run: docker compose down --volume
